#!/bin/sh
[ "$1" = --First ] && A=Y || A=N
[ -f /var/lock/bypass.lock -a $A = N ] && exit 1
LOCK=/var/lock/bypass-update.lock
[ -f $LOCK ] && exit 1
touch $LOCK
DIR=/usr/share/bypass
TMP=/tmp/bypass
T_FILE=/etc/bypass
log(){
	[ $A = N ] && echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/bypass.log
}

C=$(uci -q get bypass.@global[0].run_mode)
mkdir -p $T_FILE 2>/dev/null
mkdir -p $TMP 2>/dev/null
	if [ ! -f $T_FILE/china.txt ];then
		while !  ( curl -kLfsm 3 -o /tmp/china.txt https://op.supes.top/all_cn.txt  || curl -kLfsm 5 -o /tmp/china.txt https://cdn.jsdelivr.net/gh/sirpdboy/iplist@main/all_cn.txt || curl -kLfsm 5 -o /tmp/china.txt https://raw.githubusercontent.com/sirpdboy/iplist/all_cn.txt);do
			sleep 2
		done
	else
		 curl -kLfsm 3 -o /tmp/china.txt https://op.supes.top/all_cn.txt  || curl -kLfsm 5 -o /tmp/china.txt https://cdn.jsdelivr.net/gh/sirpdboy/iplist@main/all_cn.txt || curl -kLfsm 5 -o /tmp/china.txt https://raw.githubusercontent.com/sirpdboy/iplist/all_cn.txt
	fi
	[[ -f /tmp/china.txt && $? == 0 ]] && {
		if ! cmp -s /tmp/china.txt $T_FILE/china.txt;then
			log "By Update  : Update China IP List"
			cp -f /tmp/china.txt $TMP/china.txt
			cp -f /tmp/china.txt $T_FILE/china.txt
			[ $A = N ] && ipset list china_v4 >/dev/null 2>&1 && $DIR/chinaipset
		else
			cp -f $T_FILE/china.txt $TMP/china.txt
			log "By Update  : China IPv4 List is up to date"
		fi
        }


	if [ ! -f $T_FILE/china_v6.txt ];then

		while ! (curl -kLfsm 2 -o /tmp/china_v6.txt https://ispip.clang.cn/all_cn_ipv6.txt || curl -kLfsm 5 -o /tmp/china_v6.txt https://cdn.jsdelivr.net/gh/sirpdboy/iplist@main/all_cn_ipv6.txt);do
			sleep 2
		done
	else
		curl -kLfsm 2 -o /tmp/china_v6.txt https://ispip.clang.cn/all_cn_ipv6.txt || curl -kLfsm 5 -o /tmp/china_v6.txt https://cdn.jsdelivr.net/gh/sirpdboy/iplist@main/all_cn_ipv6.txt
	fi
	[[ -f /tmp/china_v6.txt && $? == 0 ]] && {

		if ! cmp -s /tmp/china_v6.txt  $T_FILE/china_v6.txt;then
			log "By Update  : Update China IPv6 List"
			cp -f /tmp/china_v6.txt $TMP/china_v6.txt 
			cp -f /tmp/china_v6.txt $T_FILE/china_v6.txt
			[ $A = N ] && ipset list china_v6 >/dev/null 2>&1 && $DIR/chinaipset v6
		else
	 		cp -f $T_FILE/china_v6.txt $TMP/china_v6.txt 
			log "By Update  : China IPv6 List is up to date"
		fi
	}



	if [ ! -f $T_FILE/gfw.list ];then
		while ! ( curl -kLfsm 3 -o /tmp/gfw.b64 https://op.supes.top/gfwlist.txt || curl -kLfsm 5 -o /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt  || curl -kLfsm 5  -o /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/sirpdboy/iplist@main/gfwlist.txt );do
			sleep 2
		done
	else
		curl -kLfsm 3 -o /tmp/gfw.b64 https://op.supes.top/gfwlist.txt || curl -Lfso /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt  || curl -Lfso  /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/sirpdboy/iplist@main/gfwlist.txt 
	fi
	if [[ -f /tmp/gfw.b64 && $? == 0 ]];then
		$DIR/gfw
		if ! cmp -s /tmp/gfwnew.txt  $T_FILE/gfw.list ;then
			cp -f /tmp/gfwnew.txt $TMP/gfw.list 
			cp -f /tmp/gfwnew.txt $T_FILE/gfw.list
			log "By Update  : Update GFW List"
			[ $A = N ] && /etc/init.d/bypass restart
	else
		cp -f $T_FILE/gfw.list $TMP/gfw.list 
		log "By Update  : GFW List is up to date"
	fi
    fi
rm -f $LOCK /tmp/china*.txt /tmp/gfwnew.txt
[ $A = Y ] && /etc/init.d/bypass restart &
