#!/bin/sh
#
# Copyright (C) 2013-2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

json_is_a network object && exit 0

ETHNUM=$(ls /sys/class/net/ | grep eth | wc -l)
if [ $ETHNUM == 1 ]; then
    ucidef_set_interface_lan 'eth0'
else
    LAST_ETH=$(ls /sys/class/net/ | grep eth | sort | tail -n 1)
    [ -d /sys/class/net/$LAST_ETH ] && ucidef_set_interface_wan "$LAST_ETH"
    interface=""
    for eth_interface in /sys/class/net/eth*
    do
        [ "$eth_interface" != "/sys/class/net/$LAST_ETH" ] && interface=$interface" "${eth_interface##*/}
    done
    interface=$(echo "$interface" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    [ -n "$interface" ] && ucidef_set_interface_lan "$interface"
fi
board_config_flush

exit 0
