#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

#rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
#rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
#rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

sed -i 's/\"services\"/\"control\"/g' /usr/lib/lua/luci/controller/wol.lua
sed -i 's/\"system\"/\"control\"/g' /usr/lib/lua/luci/controller/autoreboot.lua
sed -i 's/\"system\"/\"control\"/g' /usr/lib/lua/luci/controller/autopoweroff.lua
sed -i 's/\"network\"/\"control\"/g' /usr/lib/lua/luci/controller/eqos.lua

ln -sf /sbin/ip /usr/bin/ip

sed -i 's/downloads.openwrt.org/openwrt.proxy.ustclug.org/g' /etc/opkg/distfeeds.conf
sed -i 's/http:/https:/g' /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
sed -i 's/eth0/eth0 eth2 eth3 eth4 eth5/g' /etc/config/network
sed -i "s/# //g" /etc/opkg/distfeeds.conf

uci set dhcp.lan.ra='server'
uci set dhcp.lan.dhcpv6='server'
uci set dhcp.lan.ra_management='1'
uci set dhcp.lan.ra_default='1'
uci commit dhcp

sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.8/g; }'  /etc/opkg/distfeeds.conf
sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
#wifi up

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='S2020.8.7 SirPdboy'" >> /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release

#uci set vsftpd.@listen[0].enable4=0
#uci commit vsftpd
#/etc/init.d/vsftpd stop

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua


/etc/modules-boot.d && ln -s ../modules.d/18-phy-broadcom
echo 'hsts=0' > /root/.wgetrc
/etc/init.d/xl2tpd stop
/etc/init.d/xl2tpd disable
/etc/init.d/mysqld stop
/etc/init.d/mysqld disable
/etc/init.d/tvheadend stop
/etc/init.d/tvheadend disable
/etc/init.d/dnsforwarder stop
/etc/init.d/dnsforwarder disable
/etc/init.d/vmtoolsd stop
/etc/init.d/vmtoolsd disable
#/etc/init.d/watchcat stop
#/etc/init.d/watchcat disable
/etc/init.d/dnscrypt-proxy stop
/etc/init.d/dnscrypt-proxy disable
/etc/init.d/igmpproxy stop
/etc/init.d/igmpproxy disable
/etc/init.d/redsocks2 stop
/etc/init.d/redsocks2 disable
/etc/init.d/banip stop
/etc/init.d/banip disable
/etc/init.d/udpxy enable
/etc/init.d/udpxy stop
/etc/init.d/wsdd2 stop
/etc/init.d/v2ray_server stop
/etc/init.d/samba4 stop
/etc/init.d/samba stop

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
